name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.25

    - name: Check out code into the Go module directory
      uses: actions/checkout@v5

    - name: Unit Test
      run: make test

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.25

    - name: Check out code into the Go module directory
      uses: actions/checkout@v5

    - name: Generate test certificates and bring up containers
      run: |
        make test-secrets
        make dep-up

    - name: Wait for Kafka to be ready
      run: |
        echo "Waiting for Kafka to be ready..."
        timeout 120 bash -c 'until nc -z localhost 9092; do sleep 2; done'
        echo "TCP connection established, checking Kafka readiness..."
        timeout 60 bash -c 'until docker logs kt-kafka-1 2>&1 | grep -q "Kafka Server started"; do sleep 2; done'
        echo "Kafka is ready!"

    - name: Integration Test
      run: |
        make setup-integration
        make test-integration

    - name: Tear down containers
      run: make dep-down
