name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: kt Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.24

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Bring up containers
      run: docker compose -f test-dependencies.yml up -d

    - name: Wait for Kafka to be ready
      run: |
        echo "Waiting for Kafka to be ready..."
        timeout 60 bash -c 'until nc -z localhost 9092; do sleep 2; done'
        echo "Kafka is ready!"

    - name: Test
      run: make test
